database:
  type: "sqlite"  # 支持 "sqlite" 或 "mysql"
  sqlite_path: "data/sqlite.db"
  mysql:
    host: "localhost"
    user: "root"
    password: "password"
    database: "test"

erniebot:
  access_token: "03a794f63c8002be85524c48337924d4d04634fe"

